import React from 'react';

export default function Main() {
  return <div>
    <main>
      <div className="content">
        <h1 className="content__heading">Lorem ipsum</h1>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus gravida facilisis erat, et fermentum mauris mollis sed. Praesent tempus nunc ac lacinia dictum. Ut consectetur iaculis est nec posuere. Suspendisse massa massa, consectetur commodo dapibus hendrerit, aliquet at lectus. Mauris nec varius massa, id varius diam. Aenean mi odio, dignissim eu libero malesuada, ullamcorper dictum enim. Aenean blandit lectus placerat aliquet laoreet. Nunc volutpat sem in magna pharetra, porttitor tempor leo ullamcorper. In quis ante nulla.</p>
        <p>Nulla feugiat neque eu pellentesque mattis. Suspendisse est dolor, porttitor non felis a, eleifend elementum diam. Maecenas convallis tincidunt nisl, vel sodales tellus laoreet in. Mauris fringilla aliquet justo, id placerat nibh porttitor at. Proin gravida sit amet diam ut ultricies. Mauris lacinia rutrum ligula, eget cursus enim accumsan eget. Nulla maximus quam in odio fringilla, sed hendrerit sapien gravida. Proin at venenatis velit, eu varius nibh. Aliquam at lectus fermentum, elementum odio vitae, porttitor elit.</p>
        <p>Nam auctor lacus id purus pulvinar euismod. Ut nec cursus augue. Nulla at elit condimentum, maximus mi vel, pretium mi. Nullam nunc eros, euismod vitae sem eu, pretium laoreet magna. In hac habitasse platea dictumst. Donec nec magna ac lorem gravida porttitor ut a sem. Pellentesque at rutrum ipsum, sit amet pulvinar tortor. Phasellus ac aliquet sem, molestie imperdiet mauris. Maecenas augue ex, lacinia non tellus non, tempor pretium risus. In porta tincidunt neque a bibendum. Fusce at dolor sed tellus venenatis ornare. Fusce eu lacus at risus imperdiet condimentum eget ut purus.</p>
        <p>Duis elementum tempor consectetur. Nulla facilisi. Sed quis gravida nisl, elementum accumsan sem. Phasellus vel ligula nec ligula ullamcorper consectetur at eget mi. Maecenas congue dictum cursus. Cras iaculis varius turpis, quis tempus nisl efficitur vel. Maecenas ac placerat orci, dapibus pretium tortor. Vivamus vel est in nisi euismod ultrices ut sed turpis. Maecenas rutrum feugiat mauris, sit amet dictum dolor aliquet sit amet. Phasellus interdum auctor imperdiet. Proin varius enim id feugiat hendrerit. Pellentesque gravida risus mollis vehicula consequat.</p>
        <p>In odio neque, dapibus non odio finibus, convallis vestibulum est. Donec metus nulla, gravida id ante sed, maximus suscipit elit. Curabitur et enim eu nisl laoreet dapibus in nec lorem. Sed eu convallis eros. Quisque ultricies mi vel commodo rhoncus. Curabitur id pharetra dui. Aliquam in porta diam, id venenatis quam.</p>
        <p>Donec tincidunt purus et cursus sodales. Suspendisse nec nisi quam. Nullam non purus sed nulla accumsan ornare vel sollicitudin massa. Proin malesuada dui erat, quis porttitor massa porta sit amet. Nam a tortor tempus, porttitor massa nec, pretium sem. Nulla sed lectus quis velit ornare fringilla ornare eu nibh. Vivamus faucibus condimentum rutrum.</p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus gravida facilisis erat, et fermentum mauris mollis sed. Praesent tempus nunc ac lacinia dictum. Ut consectetur iaculis est nec posuere. Suspendisse massa massa, consectetur commodo dapibus hendrerit, aliquet at lectus. Mauris nec varius massa, id varius diam. Aenean mi odio, dignissim eu libero malesuada, ullamcorper dictum enim. Aenean blandit lectus placerat aliquet laoreet. Nunc volutpat sem in magna pharetra, porttitor tempor leo ullamcorper. In quis ante nulla.</p>
        <p>Nulla feugiat neque eu pellentesque mattis. Suspendisse est dolor, porttitor non felis a, eleifend elementum diam. Maecenas convallis tincidunt nisl, vel sodales tellus laoreet in. Mauris fringilla aliquet justo, id placerat nibh porttitor at. Proin gravida sit amet diam ut ultricies. Mauris lacinia rutrum ligula, eget cursus enim accumsan eget. Nulla maximus quam in odio fringilla, sed hendrerit sapien gravida. Proin at venenatis velit, eu varius nibh. Aliquam at lectus fermentum, elementum odio vitae, porttitor elit.</p>
        <p>Nam auctor lacus id purus pulvinar euismod. Ut nec cursus augue. Nulla at elit condimentum, maximus mi vel, pretium mi. Nullam nunc eros, euismod vitae sem eu, pretium laoreet magna. In hac habitasse platea dictumst. Donec nec magna ac lorem gravida porttitor ut a sem. Pellentesque at rutrum ipsum, sit amet pulvinar tortor. Phasellus ac aliquet sem, molestie imperdiet mauris. Maecenas augue ex, lacinia non tellus non, tempor pretium risus. In porta tincidunt neque a bibendum. Fusce at dolor sed tellus venenatis ornare. Fusce eu lacus at risus imperdiet condimentum eget ut purus.</p>
        <p>Duis elementum tempor consectetur. Nulla facilisi. Sed quis gravida nisl, elementum accumsan sem. Phasellus vel ligula nec ligula ullamcorper consectetur at eget mi. Maecenas congue dictum cursus. Cras iaculis varius turpis, quis tempus nisl efficitur vel. Maecenas ac placerat orci, dapibus pretium tortor. Vivamus vel est in nisi euismod ultrices ut sed turpis. Maecenas rutrum feugiat mauris, sit amet dictum dolor aliquet sit amet. Phasellus interdum auctor imperdiet. Proin varius enim id feugiat hendrerit. Pellentesque gravida risus mollis vehicula consequat.</p>
        <p>Duis elementum tempor consectetur. Nulla facilisi. Sed quis gravida nisl, elementum accumsan sem. Phasellus vel ligula nec ligula ullamcorper consectetur at eget mi. Maecenas congue dictum cursus. Cras iaculis varius turpis, quis tempus nisl efficitur vel. Maecenas ac placerat orci, dapibus pretium tortor. Vivamus vel est in nisi euismod ultrices ut sed turpis. Maecenas rutrum feugiat mauris, sit amet dictum dolor aliquet sit amet. Phasellus interdum auctor imperdiet. Proin varius enim id feugiat hendrerit. Pellentesque gravida risus mollis vehicula consequat.</p>
        <p>In odio neque, dapibus non odio finibus, convallis vestibulum est. Donec metus nulla, gravida id ante sed, maximus suscipit elit. Curabitur et enim eu nisl laoreet dapibus in nec lorem. Sed eu convallis eros. Quisque ultricies mi vel commodo rhoncus. Curabitur id pharetra dui. Aliquam in porta diam, id venenatis quam.</p>
      </div>
    </main>
  </div>;
}
